export const WHOIS_SERVERS: Record<string, string> = {
  // Genel TLD'ler
  'com': 'whois.verisign-grs.com',
  'net': 'whois.verisign-grs.com',
  'org': 'whois.pir.org',
  'info': 'whois.afilias.net',
  'biz': 'whois.biz',
  'name': 'whois.nic.name',
  
  // Ülke TLD'leri
  'tr': 'whois.nic.tr',
  'uk': 'whois.nic.uk',
  'us': 'whois.nic.us',
  'de': 'whois.denic.de',
  'fr': 'whois.nic.fr',
  'it': 'whois.nic.it',
  'es': 'whois.nic.es',
  'nl': 'whois.domain-registry.nl',
  'ru': 'whois.tcinet.ru',
  'br': 'whois.registro.br',
  'ca': 'whois.cira.ca',
  'au': 'whois.auda.org.au',
  'jp': 'whois.jprs.jp',
  'cn': 'whois.cnnic.cn',
  'in': 'whois.registry.in',
  'co': 'whois.nic.co',
  'io': 'whois.nic.io',
  'me': 'whois.nic.me',
  'tv': 'whois.nic.tv',
  'xyz': 'whois.nic.xyz',
  'online': 'whois.nic.online',
  'site': 'whois.nic.site',
  'tech': 'whois.nic.tech',
  'store': 'whois.nic.store',
  'shop': 'whois.nic.shop',
  'app': 'whois.nic.google',
  'dev': 'whois.nic.google',
  'cloud': 'whois.nic.cloud',
  'digital': 'whois.nic.digital',
  'email': 'whois.nic.email',
  'host': 'whois.nic.host',
  'live': 'whois.nic.live',
  'link': 'whois.nic.link',
  'network': 'whois.nic.network',
  'press': 'whois.nic.press',
  'space': 'whois.nic.space',
  'website': 'whois.nic.website',
  'win': 'whois.nic.win',
  'work': 'whois.nic.work',
  'world': 'whois.nic.world',
  'zone': 'whois.nic.zone'
}; 